config/routes.rb
Rails.application.routes.draw do
  get 'job_app/index'
  get 'job_app/show'
  get 'job_app/new'
  get 'job_app/create'
  get 'job_app/update'
  get 'job_app/destroy'
  get 'saved_jobs/index'
  get 'saved_jobs/new'
  get 'saved_jobs/create'
  get 'saved_jobs/destroy'
  get 'users/index'
  get 'users/show'
  get 'users/update'
  devise_for :users

  unauthenticated :user do
    devise_scope :user do
      get '/' => 'pages#home'
      # get "/about" => "pages#about"
      # get "/contact" => "pages#contact"
    end
  end

  authenticated :user do
    root 'jobs#index'
  
  resources :jobs do  
    resources :user_jobs
  end

  get "jobs/:id/edit", to: "jobs#edit"
  patch "jobs/:id", to: "jobs#update"

  get "user/jobs/", to: 'jobs#posted', as: 'posted'

  resources :users,  only: [:index, :show, :update]

  resources :jobapps, only: [] do
    get :accept, on: :member
    get :decline, on: :member
    get :complete, on: :member
  end

  get '/user/:id/savedjobs', to: 'user_jobs#usersaved', as: :usersaved

  get '/user/:id/applicants', to: 'jobapps#applicant', as: :applicant

  #Job poster applicants

  get '/user/:id/applicants/accepted', to: 'jobapps#accepted', as: :accepted

  get '/user/:id/applicants/declined', to: 'jobapps#declined', as: :declined

  get '/user/:id/applicants/completed', to: 'jobapps#completed', as: :completed

  #Applied Jobs

  get '/jobs/:id/jobapps/accepted', to: 'jobapps#jobaccepted', as: :jobaccepted

  get '/jobs/:id/jobapps/declined', to: 'jobapps#jobdeclined', as: :jobdeclined

  get '/jobs/:id/jobapps/completed', to: 'jobapps#jobcompleted', as: :jobcompleted
 

  resources :jobs do  
    resources :jobapps
  end



  end
end

app/models/accepted_job.rb
class AcceptedJob < ApplicationRecord
  has_many :jobapps
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/declined_job.rb
class DeclinedJob < ApplicationRecord
  has_many :jobapps
end

app/models/job.rb
class Job < ApplicationRecord
    belongs_to :user
    has_many :user_jobs
    has_many :jobapps

    has_one_attached :photo
    
end

app/models/jobapp.rb
class Jobapp < ApplicationRecord
    belongs_to :user
    belongs_to :job

    has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :jobs
  has_many :user_jobs
  has_many :saved_jobs, through: :user_jobs, source: :job
  has_many :jobapps
  has_many :applied_jobs, through: :jobapps, source: :job
  has_many :applicants, through: :jobs, source: :jobapps

  has_one_attached :photo


end

app/models/user_job.rb
class UserJob < ApplicationRecord
    belongs_to :user
    belongs_to :job

    has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:fname, :lname, :username, :photo ])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:fname, :lname, :email, :username, :user_description, :user_address, :photo ])
  end

end

app/controllers/jobapps_controller.rb
class JobappsController < ApplicationController
  def index
    @jobapp = Jobapp.where(user_id: current_user)
    @job = Job.all
  end

  def show
  end

  def new
    @jobapp = Jobapp.new
    @job = Job.find(params[:job_id])
  end

  def create
    @jobapp = Jobapp.new(jobapp_params)
    @job = Job.find(params[:job_id])
    @jobapp.job = @job
    @jobapp.user = current_user
    @jobapp.save
    redirect_to job_jobapps_path
  end

  def update
  end

  def destroy
  end

  #Jobs listed in Applicants

  def applicant
    @applications = current_user.applicants
  end
  
  #button actions

  def accept
    @accept = Jobapp.find(params[:id])
    @accept.update_attribute(:accepted, true)
    redirect_to applicant_path(current_user)
  end

  def decline
    @decline = Jobapp.find(params[:id])
    @decline.update_attribute(:accepted, false)
    redirect_to applicant_path(current_user)
  end

  def complete
    @complete = Jobapp.find(params[:id])
    @complete.update_attribute(:complete, true)
    redirect_to applicant_path(current_user)
  end

  #Applicants menus

  def accepted
    @acceptedjobs = current_user.applicants.where(accepted: true)
  end

  def declined
    @declinedjobs = current_user.applicants.where(accepted: false)
  end

  def completed
    @completedjobs = current_user.applicants.where(complete: true)
  end

  #Jobs listed in User Applied

  def jobaccepted
    @acceptedjobs = Jobapp.where(user_id: current_user).where(accepted: true)
  end

  def jobdeclined
    @declinedjobs = Jobapp.where(user_id: current_user).where(accepted: true).where(accepted: false)
  end

  def jobcompleted
    @completedjobs = Jobapp.where(user_id: current_user).where(accepted: true).where(complete: true)
  end

  private

  def jobapp_params
    params.require(:jobapp).permit(:message, :photo)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @job = Job.all
    @saves = UserJob.new
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end
  

  def create
    @job = Job.new(job_params)
    @job.user = current_user
    if @job.save!
        redirect_to jobs_path(@job)
    else
        render 'new'
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    @job.update(job_params)
    redirect_to jobs_path(@job)
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to jobs_path(@job)
  end

  def posted
    @job = Job.where(user_id: current_user)
  end

  private

  def job_params
      params.require(:job).permit(:user_id, :job_title, :job_description, :job_long_description, :job_location, :job_price, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/saved_jobs_controller.rb
class SavedJobsController < ApplicationController
  before_action :find_job, only: [:create]

  def index
    @job = SavedJob.where(user_id: current_user)
  end

  def new
    @job = SavedJob.new
  end

  def create
    if already_saved?
      flash[:notice] = "You can't save more than once"
      else
      @job.saved_jobs.create(user_id: current_user.id, job_id:params[:job_id])
    end
    redirect_to jobs_path
  end

  def destroy
  end

  def usersaved
    @job = current_user.saved_jobs
  end

  private

  def find_job
    @job = Job.find(params[:job_id])
  end
  
  def already_saved?
    SavedJob.where(user_id: current_user.id, job_id:params[:job_id]).exists?
  end

  def job_params
    params.require(:job).permit(:user_id, :job_title, :job_description, :job_long_description, :job_location, :job_price, :photo)
end

end

app/controllers/user_jobs_controller.rb
class UserJobsController < ApplicationController
  before_action :find_job, only: [:create]

  def index
    @job = UserJob.where(user_id: current_user)
  end

  def new
    @job = UserJob.new
  end

  def create
    if already_saved?
      flash[:notice] = "You can't save more than once"
      else
      @job.user_jobs.create(user_id: current_user.id, job_id:params[:job_id])
    end
    redirect_to jobs_path
  end

  def destroy
  end

  def usersaved
    @jobs = current_user.saved_jobs
  end

  private

  def find_job
    @job = Job.find(params[:job_id])
  end
  
  def already_saved?
    UserJob.where(user_id: current_user.id, job_id:params[:job_id]).exists?
  end

  def job_params
    params.require(:job).permit(:user_id, :job_title, :job_description, :job_long_description, :job_location, :job_price, :photo)
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(current_user)
  end

  private
  
  def user_params
    params.require(:user).permit(:fname, :lname, :username, :user_description, :user_address, :password, :password_confirmation, :photo)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/jobapps/accepted.html.erb
<div class="container-job-index">
    <h1>All Accepted Applicants</h1>
    <p>All applicants who have been accepted should appear here</p>
    <div class="flex">
        <%= link_to "All", applicant_path(current_user) %>
        <p> | </p>
        <%= link_to "Accepted", accepted_path(current_user) %>
        <p> | </p>
        <%= link_to "Declined", declined_path(current_user) %>
        <p> | </p>
        <%= link_to "Completed", completed_path(current_user) %>
    </div>
    <% @acceptedjobs.each do |accepted| %>
    <div class="applicant-card">

        <div class="applicant-info">
        <div class="flex">
            <% if accepted.user.photo.attached? %>
                <%= cl_image_tag accepted.user.photo.key, class: "applicant-image-small" %>
            <% end %>
            <div>
                <h3 class="job-card-title"><%= accepted.user.fname %> <%= accepted.user.lname %></h3>
                <p class="job-card-description">Applying for: <%= accepted.job.job_title %></p>
                <div class="location-icon-width">
                    <i class="fas fa-map-pin icon"><span class="icon-text"><%= accepted.user.user_address %></span></i>
                </div>
                <p class="">"<%= accepted.message %>"</p>
                
            </div>
        </div>
            <div class="flex accept-decline">
                    <%= link_to "Completed", complete_jobapp_path(accepted), class: "button-card-applicant" %>
                </div>
        </div>
    </div>
    <% end %>
</div>

app/views/jobapps/applicant.html.erb
<div class="container-job-index">
    <h1>All Applicants to my jobs</h1>
    <p>All applicants to your jobs should appear here</p>
    <div class="flex">
        <%= link_to "All", applicant_path(current_user) %>
        <p> | </p>
        <%= link_to "Accepted", accepted_path(current_user) %>
        <p> | </p>
        <%= link_to "Declined", declined_path(current_user) %>
        <p> | </p>
        <%= link_to "Completed", completed_path(current_user) %>
    </div>
    <% @applications.each do |application| %>
    <div class="applicant-card">

        <div class="applicant-info">
        <div class="flex">
            <% if application.user.photo.attached? %>
                <%= cl_image_tag application.user.photo.key, class: "applicant-image-small" %>
            <% end %>
            <div>
                <h3 class="job-card-title"><%= application.user.fname %> <%= application.user.lname %></h3>
                <p class="job-card-description">Applying for: <%= application.job.job_title %></p>
                <div class="location-icon-width">
                    <i class="fas fa-map-pin icon"><span class="icon-text"><%= application.user.user_address %></span></i>
                </div>
                <p class="">"<%= application.message %>"</p>
                
            </div>
        </div>
            <div class="flex accept-decline">
                    <%= link_to "Accept", accept_jobapp_path(application), class: "button-card-applicant" %>
                    <%= link_to "Decline", decline_jobapp_path(application), class: "button-card-applicant" %>
                </div>
        </div>
    </div>
    <% end %>
</div>

app/views/jobapps/completed.html.erb
<div class="container-job-index">
    <h1>All Completed Jobs by Applicants</h1>
    <p>All applicants who have completed jobs should appear here</p>
    <div class="flex">
        <%= link_to "All", applicant_path(current_user) %>
        <p> | </p>
        <%= link_to "Accepted", accepted_path(current_user) %>
        <p> | </p>
        <%= link_to "Declined", declined_path(current_user) %>
        <p> | </p>
        <%= link_to "Completed", completed_path(current_user) %>
    </div>
    <% @completedjobs.each do |completed| %>
    <div class="applicant-card">

        <div class="applicant-info">
        <div class="flex">
            <% if completed.user.photo.attached? %>
                <%= cl_image_tag completed.user.photo.key, class: "applicant-image-small" %>
            <% end %>
            <div>
                <h3 class="job-card-title"><%= completed.user.fname %> <%= completed.user.lname %></h3>
                <p class="job-card-description">Applying for: <%= completed.job.job_title %></p>
                <div class="location-icon-width">
                    <i class="fas fa-map-pin icon"><span class="icon-text"><%= completed.user.user_address %></span></i>
                </div>
                <p class="">"<%= completed.message %>"</p>
                
            </div>
        </div>
        </div>
    </div>
    <% end %>
</div>

app/views/jobapps/create.html.erb
<h1>JobApp#create</h1>
<p>Find me in app/views/job_app/create.html.erb</p>

app/views/jobapps/declined.html.erb
<div class="container-job-index">
    <h1>All Declined Applicants</h1>
    <p>All applicants who have been declined should appear here</p>
    <div class="flex">
        <%= link_to "All", applicant_path(current_user) %>
        <p> | </p>
        <%= link_to "Accepted", accepted_path(current_user) %>
        <p> | </p>
        <%= link_to "Declined", declined_path(current_user) %>
        <p> | </p>
        <%= link_to "Completed", completed_path(current_user) %>
    </div>
    <% @declinedjobs.each do |declined| %>
    <div class="applicant-card">

        <div class="applicant-info">
        <div class="flex">
            <% if declined.user.photo.attached? %>
                <%= cl_image_tag declined.user.photo.key, class: "applicant-image-small" %>
            <% end %>
            <div>
                <h3 class="job-card-title"><%= declined.user.fname %> <%= declined.user.lname %></h3>
                <p class="job-card-description">Applying for: <%= declined.job.job_title %></p>
                <div class="location-icon-width">
                    <i class="fas fa-map-pin icon"><span class="icon-text"><%= declined.user.user_address %></span></i>
                </div>
                <p class="">"<%= declined.message %>"</p>
                
            </div>
        </div>
            <div class="flex accept-decline">
                    <%= link_to "Completed", accept_jobapp_path(declined), class: "button-card-applicant" %>
                </div>
        </div>
    </div>
    <% end %>
</div>

app/views/jobapps/destroy.html.erb
<h1>JobApp#destroy</h1>
<p>Find me in app/views/job_app/destroy.html.erb</p>

app/views/jobapps/index.html.erb
<div class="container-job-index">
    <h1>All Applied Jobs</h1>
    <p>All jobs you applied to should appear here</p>
    <div class="flex">
        <%= link_to "All", job_jobapps_path(current_user) %>
        <p> | </p>
        <%= link_to "Accepted", jobaccepted_path(current_user) %>
        <p> | </p>
        <%= link_to "Declined", jobdeclined_path(current_user) %>
        <p> | </p>
        <%= link_to "Completed", jobcompleted_path(current_user) %>
    </div>
    <% @jobapp.each do |jobapp| %>
    <div class="job-card">
        <div class="job-image">
            <% if jobapp.job.photo.attached? %>
                <%= cl_image_tag jobapp.job.photo.key, class: "job-image" %>
            <% end %>
        </div>
        <div class="job-info">
            <h3 class="job-card-title"><%= jobapp.job.job_title %></h3>
            <p class="job-card-description"><%= jobapp.job.job_description %></p>
            <div class="flex">
                <p class="job-card-description padding-right">Applicant:<%= jobapp.user.fname %></p>
                <p class="job-card-description">Job Poster:<%= jobapp.job.user.fname %></p>
            </div>
            <p class="job-card-price">Paying R <%= jobapp.job.job_price %></p>
            <div class="job-view-button flex end card-icons">
                <div class="location-icon-width">
                    <i class="fas fa-map-pin icon"><span class="icon-text"><%= jobapp.job.job_location %></span></i>
                </div>
                <%= link_to job_path(jobapp), method: :delete do %>
                    <i class="fas fa-trash icon"></i>
                <% end %>
                <%= link_to "View Job", job_path(jobapp), class: "button-card" %>
            </div>
        </div>
    </div>
    <% end %>
</div>

app/views/jobapps/jobaccepted.html.erb
<div class="container-job-index">
    <h1>All Applied Jobs</h1>
    <p>All jobs you applied which were accepted to should appear here</p>
    <div class="flex">
        <%= link_to "All", job_jobapps_path(current_user) %>
        <p> | </p>
        <%= link_to "Accepted", jobaccepted_path(current_user) %>
        <p> | </p>
        <%= link_to "Declined", jobdeclined_path(current_user) %>
        <p> | </p>
        <%= link_to "Completed", jobcompleted_path(current_user) %>
    </div>
    <% @acceptedjobs.each do |accepted| %>
    <div class="job-card">
        <div class="job-image">
            <% if accepted.job.photo.attached? %>
                <%= cl_image_tag accepted.job.photo.key, class: "job-image" %>
            <% end %>
        </div>
        <div class="job-info">
            <h3 class="job-card-title"><%= accepted.job.job_title %></h3>
            <p class="job-card-description"><%= accepted.job.job_description %></p>
            <div class="flex">
                <p class="job-card-description padding-right">Applicant:<%= accepted.user.fname %></p>
                <p class="job-card-description">Job Poster:<%= accepted.job.user.fname %></p>
            </div>
            <p class="job-card-price">Paying R <%= accepted.job.job_price %></p>
            <div class="job-view-button flex end card-icons">
                <div class="location-icon-width">
                    <i class="fas fa-map-pin icon"><span class="icon-text"><%= accepted.job.job_location %></span></i>
                </div>
                <%= link_to job_path(accepted), method: :delete do %>
                    <i class="fas fa-trash icon"></i>
                <% end %>
                <%= link_to "View Job", job_path(accepted), class: "button-card" %>
            </div>
        </div>
    </div>
    <% end %>
</div>

app/views/jobapps/jobcompleted.html.erb
<div class="container-job-index">
    <h1>All Completed Jobs</h1>
    <p>All jobs you completed should appear here</p>
    <div class="flex">
        <%= link_to "All", job_jobapps_path(current_user) %>
        <p> | </p>
        <%= link_to "Accepted", jobaccepted_path(current_user) %>
        <p> | </p>
        <%= link_to "Declined", jobdeclined_path(current_user) %>
        <p> | </p>
        <%= link_to "Completed", jobcompleted_path(current_user) %>
    </div>
        <% @completedjobs.each do |completed| %>
    <div class="job-card">
        <div class="job-image">
            <% if completed.job.photo.attached? %>
                <%= cl_image_tag completed.job.photo.key, class: "job-image" %>
            <% end %>
        </div>
        <div class="job-info">
            <h3 class="job-card-title"><%= completed.job.job_title %></h3>
            <p class="job-card-description"><%= completed.job.job_description %></p>
            <div class="flex">
                <p class="job-card-description padding-right">Applicant:<%= completed.user.fname %></p>
                <p class="job-card-description">Job Poster:<%= completed.job.user.fname %></p>
            </div>
            <p class="job-card-price">Paying R <%= completed.job.job_price %></p>
            <div class="job-view-button flex end card-icons">
                <div class="location-icon-width">
                    <i class="fas fa-map-pin icon"><span class="icon-text"><%= completed.job.job_location %></span></i>
                </div>
                <%= link_to job_path(completed), method: :delete do %>
                    <i class="fas fa-trash icon"></i>
                <% end %>
                <%= link_to "View Job", job_path(completed), class: "button-card" %>
            </div>
        </div>
    </div>
    <% end %>
</div>

app/views/jobapps/jobdeclined.html.erb
<div class="container-job-index">
    <h1>All Declined Jobs</h1>
    <p>All jobs you applied to but were declined should appear here</p>
    <div class="flex">
        <%= link_to "All", job_jobapps_path(current_user) %>
        <p> | </p>
        <%= link_to "Accepted", jobaccepted_path(current_user) %>
        <p> | </p>
        <%= link_to "Declined", jobdeclined_path(current_user) %>
        <p> | </p>
        <%= link_to "Completed", jobcompleted_path(current_user) %>
    </div>
    <% @declinedjobs.each do |declined| %>
    <div class="job-card">
        <div class="job-image">
            <% if declined.job.photo.attached? %>
                <%= cl_image_tag declined.job.photo.key, class: "job-image" %>
            <% end %>
        </div>
        <div class="job-info">
            <h3 class="job-card-title"><%= declined.job.job_title %></h3>
            <p class="job-card-description"><%= declined.job.job_description %></p>
            <div class="flex">
                <p class="job-card-description padding-right">Applicant:<%= declined.user.fname %></p>
                <p class="job-card-description">Job Poster:<%= declined.job.user.fname %></p>
            </div>
            <p class="job-card-price">Paying R <%= declined.job.job_price %></p>
            <div class="job-view-button flex end card-icons">
                <div class="location-icon-width">
                    <i class="fas fa-map-pin icon"><span class="icon-text"><%= declined.job.job_location %></span></i>
                </div>
                <%= link_to job_path(declined), method: :delete do %>
                    <i class="fas fa-trash icon"></i>
                <% end %>
                <%= link_to "View Job", job_path(declined), class: "button-card" %>
            </div>
        </div>
    </div>
    <% end %>
</div>

app/views/jobapps/show.html.erb
<h1>JobApp#show</h1>
<p>Find me in app/views/job_app/show.html.erb</p>

app/views/jobs/index.html.erb
<div class="container-job-index">
    <h1>All Jobs</h1>
    <p>All jobs should appear here</p>
    <% @job.each do |job| %>
    <div class="job-card">
        <div class="job-image">
            <% if job.photo.attached? %>
                <%= cl_image_tag job.photo.key, class: "job-image" %>
            <% end %>
        </div>
        <div class="job-info">
            <h3 class="job-card-title"><%= job.job_title %></h3>
            <p class="job-card-description"><%= job.job_description %></p>
            <p class="job-card-price">Paying R <%= job.job_price %></p>
            <div class="job-view-button flex end card-icons">
                <div class="location-icon-width">
                    <i class="fas fa-map-pin icon"><span class="icon-text"><%= job.job_location %></span></i>
                </div>
                <%= link_to job_path(job), method: :delete do %>
                    <i class="fas fa-trash icon"></i>
                <% end %>
                <%= link_to edit_job_path(job) do %>
                    <i class="far fa-edit icon"></i>
                <% end %>
                    <%= simple_form_for @saves, url: job_user_jobs_path(job.id), method: :post do |f| %>
                        <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
                        <%= f.input :job_id, as: :hidden, input_html: { value: job.id } %>
                            <%= button_tag type: 'submit', class: "no-styling", id: "" do %>
                            <i class="far fa-bookmark icon"></i>
                        <% end %>
                <% end %>
                <%= link_to "View Job", job_path(job), class: "button-card" %>
            </div>
        </div>
    </div>
    <% end %>
</div>

app/views/jobs/posted.html.erb
<div class="container-job-index">
    <h1>All My Posted Jobs</h1>
    <p>All jobs should appear here</p>
    <% @job.each do |job| %>
    <div class="job-card">
        <div class="job-image">
            <% if job.photo.attached? %>
                <%= cl_image_tag job.photo.key, class: "job-image" %>
            <% end %>
        </div>
        <div class="job-info">
            <h3 class="job-card-title"><%= job.job_title %></h3>
            <p class="job-card-description"><%= job.job_description %></p>
            <p class="job-card-price">Paying R <%= job.job_price %></p>
            <div class="job-view-button flex end card-icons">
                <div class="location-icon-width">
                    <i class="fas fa-map-pin icon"><span class="icon-text"><%= job.job_location %></span></i>
                </div>
                <%= link_to job_path(job), method: :delete do %>
                    <i class="fas fa-trash icon"></i>
                <% end %>
                <%= link_to edit_job_path(job) do %>
                    <i class="far fa-edit icon"></i>
                <% end %>
                <%= link_to "View Job", job_path(job), class: "button-card" %>
            </div>
        </div>
    </div>
    <% end %>
</div>

app/views/jobs/update.html.erb
<h1>Jobs#update</h1>
<p>Find me in app/views/jobs/update.html.erb</p>

app/views/saved_jobs/usersaved.html.erb
<div class="container-job-index">
    <h1>My Saved Jobs</h1>
    <p>All saved jobs should appear here</p>
    <% @job.each do |job| %>
    <div class="job-card">
        <div class="job-image">
            <% if job.photo.attached? %>
                <%= cl_image_tag job.photo.key, class: "job-image" %>
            <% end %>
        </div>
        <div class="job-info">
            <h3 class="job-card-title"><%= job.job_title %></h3>
            <p class="job-card-description"><%= job.job_description %></p>
            <p class="job-card-price">Paying R <%= job.job_price %></p>
            <div class="job-view-button flex end card-icons">
                <div class="location-icon-width">
                    <i class="fas fa-map-pin icon"><span class="icon-text"><%= job.job_location %></span></i>
                </div>
                <%= link_to job_path(job), method: :delete do %>
                    <i class="fas fa-trash icon"></i>
                <% end %>
                <%= link_to edit_job_path(job) do %>
                    <i class="far fa-edit icon"></i>
                <% end %>
                <%= link_to edit_job_path(job) do %>
                    <i class="far fa-bookmark icon"></i>
                <% end %>
                <%= link_to "View Job", job_path(job), class: "button-card" %>
            </div>
        </div>
    </div>
    <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <h3 class="text-logo">AnythingGoes</h3>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "All Users", users_index_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "All Jobs", jobs_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Applied Jobs", job_jobapps_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Posted Jobs", posted_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Applicants", applicant_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Post a Job", new_job_path , class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Saved Jobs", usersaved_path(current_user) , class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
        
        <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: " avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "User Settings", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "About", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact Us", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>